name: ci

on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm i
            - name: Build application
              run: npm run build
            - name: Run tests
              run: npm run test
              env:
                  NODE_ENV: "test"
                  PORT: 8000
                  API_KEY: "test"
                  API_NAME: "test"
                  RATE_LIMIT_DURATION_MS: 1000
                  RATE_LIMIT_MAX_REQUESTS: 5
                  # Third Party Services
                  PG_URL: "postgres://test:test@localhost:5432/postgres"
                  REDIS_URL: "redis://localhost:6379"
                  AMQP_URL: "amqp://test:test@localhost:5672"
                  MINIO_URL: "127.0.0.1"
                  MINIO_PORT: 9000
                  MINIO_ACCESS_KEY: "miniousertest"
                  MINIO_SECRET_KEY: "miniousertest"
                  # Tests Behaviours
                  ENABLE_TEST_RABBITMQ_CONTAINER: true
                  ENABLE_TEST_MINIO_CONTAINER: true
                  ENABLE_TEST_REDIS_CONTAINER: true
                  ENABLE_TEST_POSTGRES_CONTAINER: true
                  DEBUG_TEST: false
